version: "3.7"
services:
  # GERENCIADOR DE CONTAINERS
  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: portainer
    ports:
    - "9000:9000"
     volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainerdata:/data
    
volumes:
  portainerdata: