#DOCKERFILE PARA TESTES
FROM node:12.16.2

# INSTALL IONIC AND ANGULAR
RUN npm install -g @angular/cli @ionic/cli
RUN echo y
COPY . ./tmp

RUN ls tmp/

RUN cp tmp/docker-entrypoint.sh /usr/local/bin/ && \
    chmod +x /usr/local/bin/docker-entrypoint.sh

RUN ls /usr/local/bin/

#WORKDIR
WORKDIR /tmp

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
